Homework4
taraskin07/Homework_repo pull request #8
Opened 2021-04-29 14:40 UTC by taraskin07

2021-04-30 11:59 UTC, iamthen0ise requested changes
есть что доделать для зачета, в целом эта домашка уже получше. доделай и присылай уже хороший код на зачет.

2021-04-30 11:59 UTC, iamthen0ise commented on homework4/tasks/task_3_get_print_output.py
> +    if text.startswith("error"):
попробуй посмотреть как более нативно писать в std потоки без print. все-таки принт это расширенная обертка над stdout. так тоже можно, но более нативно было бы еще лучше.

2021-04-30 11:59 UTC, iamthen0ise commented on homework4/tests/test_task_3_get_print_output.py
> +def my_precious_logger(text: str):
нужно импортировать функцию из задачи

2021-04-30 11:59 UTC, iamthen0ise commented on homework4/tasks/task_3_get_print_output.py
> +    if text.startswith("error"):
++ error может быть написан любым кейсом и тогда тесты не пройдут и в нужны поток ничего не пойдет

2021-04-30 11:59 UTC, iamthen0ise commented on homework4/tests/test_task_4_doctest.py
> +def fizzbuzz(n: int) -> List[str]:
нет, это скорее нужно унести в сам таск)

2021-04-30 11:59 UTC, iamthen0ise commented on homework4/tests/test_task_4_doctest.py
> +if __name__ == "__main__":
так в тестах тоже делать нельзя. 

лучше посмотри побольше про доктест, не обязательно только в родной доке, и допиши само задание.

2021-05-05 12:12 UTC, taraskin07 commented on homework4/tasks/task_3_get_print_output.py
> +    if text.startswith("error"):
тут разобрался, всё в нативном виде!

2021-05-05 12:12 UTC, taraskin07 commented on homework4/tests/test_task_3_get_print_output.py
> +def my_precious_logger(text: str):
сделано!

2021-05-05 12:12 UTC, taraskin07 commented on homework4/tests/test_task_4_doctest.py
> +def fizzbuzz(n: int) -> List[str]:
удалил тестовый файл в папке tests, теперь всё в tasks для этого задания

2021-05-05 12:14 UTC, taraskin07 commented on homework4/tests/test_task_4_doctest.py
> +if __name__ == "__main__":
Посмотрел примеры, переделал, написал инструкцию для запуска программы и доктеста к ней(там файл пустой вроде был, notepad по умолчанию не сохраняет изменения, там не досмотрел)

2021-05-07 14:18 UTC, merged