homework5
taraskin07/Homework_repo pull request #9
Opened 2021-05-11 14:22 UTC by taraskin07

2021-05-13 10:18 UTC, i-n-samartsev commented on homework5/tasks/oop_1.py
> +        # print(self.text)
здесь и далее по тексту - отладочного кода в конечном результате на должно быть. 
Если нужно логгирование которое может отображаться или не может - используй модуль logging, и выводи с нужным уровнем логгирования. Пользователь, пользующийся твоей библиотекой сам потом при желании изменит уровень логгирования чтобы получить более подробный вывод, если ему это понадобится. пример:

```
import logging
logger = logging.getLogger(__name__)

def something(a, b):
    logger.debug('Inside function "something"')
    logger.debug(f'received arguments: {a}, {b}')
    return a \ b
```

если пользователь использует уровень info (по умолчанию), debug информация не будет выведена. А если установит на debug, то он ее увидит.

2021-05-13 10:18 UTC, i-n-samartsev commented on homework5/tasks/oop_1.py
> +        # print(self.text)
Применительно к твоему коду - здесь и далее такие комментарии надо убрать

2021-05-13 10:20 UTC, i-n-samartsev commented on homework5/tasks/oop_1.py
> +class Homework:
Давай сразу же начнем документировать свои классы правильно.

в питонячем мире принято использовать формат документации утилиты sphinx (вот неплохая статья по этому https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html ). Огромное преимущество такого стандартизованного описания в том что по такой докстринге может генерироваться автоматически документация в любых разных форматах (например для отображения на веб-страницах). Практически все python проекты (включая документацию самого питона) используют для этого как раз sphinx.

исправь документацию своих классов и их методов в формат sphinx

2021-05-13 10:24 UTC, i-n-samartsev commented on homework5/tasks/oop_1.py
> +    def do_homework(self, Homework):
1) Когда я вижу литерал, начинающийся с прописной буквы (Homework) я думаю что это класс. в твоем случае это не класс, а объект.
2) используя то же имя (Homework) что и ранее определено (класс Homework) в качестве параметра, ты можешь внести ошибку. избегай этого.

В данном конкретном случае параметр Homework (и атрибут self.Homework) надо будет исправить на homework

2021-05-13 10:37 UTC, i-n-samartsev commented on homework5/tasks/save_original_info.py
> +def print_result(func):
Перечитай условия задачи, функцию print_result изменять нельзя. тебе надо написать отдельный декоратор save_original_info

2021-05-13 10:48 UTC, i-n-samartsev commented on homework5/tests/test_oop_1.py
> +from homework5.tasks.oop_1 import *
здесь (и везде) не используй import *. Это (как например использование goto в других языках программирования)  для особых случаев. В обычном коде импорт со звездой будет серьезной ошибкой.

2021-05-13 10:48 UTC, i-n-samartsev requested changes
исправить согласно комментариям

2021-05-20 14:40 UTC, taraskin07 commented on homework5/tasks/oop_1.py
> +        # print(self.text)
Спасибо! Теперь буду знать про логгер.

2021-05-20 14:41 UTC, taraskin07 commented on homework5/tasks/oop_1.py
> +    def do_homework(self, Homework):
Исправил

2021-05-20 14:43 UTC, taraskin07 commented on homework5/tests/test_oop_1.py
> +from homework5.tasks.oop_1 import *
Сделал

2021-05-20 14:43 UTC, taraskin07 commented on homework5/tasks/oop_1.py
> +class Homework:
Спасибо!

2021-05-20 14:44 UTC, taraskin07 commented on homework5/tasks/save_original_info.py
> +def print_result(func):
Сейчас исправлю

2021-05-20 16:54 UTC, taraskin07 commented
Всё исправлено!

2021-06-06 13:02 UTC, i-n-samartsev commented on homework5/tasks/save_original_info.py
> +        setattr(new_func, "__name__", function.__name__)
чем такой подход лучше или хуже чем написать вот так?
    new_func.__name__ = function.__name__  ?

2021-06-06 13:03 UTC, i-n-samartsev requested changes
изменить setattr на явное присвоение

2021-06-09 08:40 UTC, closed without merging